#!/usr/bin/env bash
# scripts/write-contract-config.sh
# Reads contracts/out/deployed-addresses.json and writes src/contractConfig.ts.
# Run this after: forge script contracts/script/Deploy.s.sol:Deploy --broadcast ...
set -euo pipefail

JSON="contracts/out/deployed-addresses.json"

if [ ! -f "$JSON" ]; then
  echo "Error: $JSON not found. Run the Deploy script first." >&2
  exit 1
fi

# Parse addresses from JSON (using python3, available on macOS by default)
TREASURY=$(python3 -c "import json,sys; d=json.load(open('$JSON')); print(d['treasury'])")
INVOICE_NFT=$(python3 -c "import json,sys; d=json.load(open('$JSON')); print(d['invoiceNFT'])")
COLLATERAL_MANAGER=$(python3 -c "import json,sys; d=json.load(open('$JSON')); print(d['collateralManager'])")
UNIT_CLAIM=$(python3 -c "import json,sys; d=json.load(open('$JSON')); print(d['unitClaim'])")
GRID_MANAGER=$(python3 -c "import json,sys; d=json.load(open('$JSON')); print(d['gridManager'])")
INVOICE_MANAGER=$(python3 -c "import json,sys; d=json.load(open('$JSON')); print(d['invoiceManager'])")
COINTAG_MANAGER=$(python3 -c "import json,sys; d=json.load(open('$JSON')); print(d['coinTagManager'])")
PAYMENT_MANAGER=$(python3 -c "import json,sys; d=json.load(open('$JSON')); print(d['paymentManager'])")

OUT="src/contractConfig.ts"

cat > "$OUT" << TYPESCRIPT
// AUTO-GENERATED by scripts/write-contract-config.sh - do not edit by hand
// Source: $JSON
// Chain: Arc Testnet (5042002)
import { requireChain } from '@/onchain-facts'

export const ARC_TESTNET_ID = 5042002

requireChain(ARC_TESTNET_ID) // validates chain exists

// ── Deployed addresses ────────────────────────────────────────────────────
export const CONTRACT_ADDRESSES = {
  treasury:          '${TREASURY}' as \`0x\${string}\`,
  invoiceNFT:        '${INVOICE_NFT}' as \`0x\${string}\`,
  collateralManager: '${COLLATERAL_MANAGER}' as \`0x\${string}\`,
  unitClaim:         '${UNIT_CLAIM}' as \`0x\${string}\`,
  gridManager:       '${GRID_MANAGER}' as \`0x\${string}\`,
  invoiceManager:    '${INVOICE_MANAGER}' as \`0x\${string}\`,
  coinTagManager:    '${COINTAG_MANAGER}' as \`0x\${string}\`,
  paymentManager:    '${PAYMENT_MANAGER}' as \`0x\${string}\`,
} as const

// ── Per-contract exports (address + minimal ABI) ──────────────────────────

export const TREASURY_CONTRACT = {
  address: CONTRACT_ADDRESSES.treasury,
  abi: [
    { type: 'function', name: 'receiveRevenue', stateMutability: 'nonpayable',
      inputs: [{ name: 'stablecoin', type: 'address' }, { name: 'amount', type: 'uint256' }], outputs: [] },
    { type: 'function', name: 'withdraw', stateMutability: 'nonpayable',
      inputs: [{ name: 'stablecoin', type: 'address' }, { name: 'to', type: 'address' }, { name: 'amount', type: 'uint256' }], outputs: [] },
    { type: 'function', name: 'totalRevenueCollected', stateMutability: 'view',
      inputs: [{ name: 'stablecoin', type: 'address' }], outputs: [{ type: 'uint256' }] },
    { type: 'function', name: 'platformRecipient', stateMutability: 'view',
      inputs: [], outputs: [{ type: 'address' }] },
    { type: 'event', name: 'RevenueReceived',
      inputs: [{ name: 'stablecoin', type: 'address', indexed: true }, { name: 'amount', type: 'uint256' }] },
    { type: 'event', name: 'WithdrawalExecuted',
      inputs: [{ name: 'stablecoin', type: 'address', indexed: true }, { name: 'to', type: 'address', indexed: true }, { name: 'amount', type: 'uint256' }] },
  ] as const,
}

export const INVOICE_NFT_CONTRACT = {
  address: CONTRACT_ADDRESSES.invoiceNFT,
  abi: [
    { type: 'function', name: 'mintInvoiceNFT', stateMutability: 'nonpayable',
      inputs: [{ name: 'invoiceId', type: 'uint256' }, { name: 'creator', type: 'address' }, { name: 'metadataURI', type: 'string' }],
      outputs: [{ name: 'tokenId', type: 'uint256' }] },
    { type: 'function', name: 'getInvoiceNFTData', stateMutability: 'view',
      inputs: [{ name: 'tokenId', type: 'uint256' }],
      outputs: [{ type: 'tuple', components: [
        { name: 'invoiceId', type: 'uint256' },
        { name: 'creator', type: 'address' },
        { name: 'invoiceValue', type: 'uint256' },
        { name: 'stablecoin', type: 'address' },
        { name: 'dueDate', type: 'uint64' },
        { name: 'tokenizedAt', type: 'uint64' },
        { name: 'collateralPool', type: 'address' },
        { name: 'gridBoard', type: 'address' },
        { name: 'totalUnits', type: 'uint16' },
        { name: 'status', type: 'uint8' },
        { name: 'metadataURI', type: 'string' },
        { name: 'debtorRef', type: 'bytes32' },
      ]}] },
    { type: 'function', name: 'ownerOf', stateMutability: 'view',
      inputs: [{ name: 'tokenId', type: 'uint256' }], outputs: [{ type: 'address' }] },
    { type: 'function', name: 'isTransferable', stateMutability: 'view',
      inputs: [{ name: 'tokenId', type: 'uint256' }], outputs: [{ type: 'bool' }] },
    { type: 'event', name: 'InvoiceNFTMinted',
      inputs: [{ name: 'invoiceId', type: 'uint256', indexed: true }, { name: 'to', type: 'address', indexed: true }, { name: 'metadataURI', type: 'string' }] },
    { type: 'event', name: 'InvoiceTokenized',
      inputs: [{ name: 'invoiceId', type: 'uint256', indexed: true }, { name: 'creator', type: 'address', indexed: true }] },
  ] as const,
}

export const COLLATERAL_MANAGER_CONTRACT = {
  address: CONTRACT_ADDRESSES.collateralManager,
  abi: [
    { type: 'function', name: 'depositInitial', stateMutability: 'nonpayable',
      inputs: [{ name: 'invoiceId', type: 'uint256' }, { name: 'stablecoin', type: 'address' }, { name: 'creator', type: 'address' }, { name: 'amount', type: 'uint256' }], outputs: [] },
    { type: 'function', name: 'contribute', stateMutability: 'nonpayable',
      inputs: [{ name: 'invoiceId', type: 'uint256' }, { name: 'amount', type: 'uint256' }], outputs: [] },
    { type: 'function', name: 'payoutClaim', stateMutability: 'nonpayable',
      inputs: [{ name: 'invoiceId', type: 'uint256' }, { name: 'recipient', type: 'address' }], outputs: [{ name: 'payout', type: 'uint256' }] },
    { type: 'function', name: 'totalCollateral', stateMutability: 'view',
      inputs: [{ name: 'invoiceId', type: 'uint256' }], outputs: [{ type: 'uint256' }] },
    { type: 'function', name: 'pools', stateMutability: 'view',
      inputs: [{ name: 'invoiceId', type: 'uint256' }],
      outputs: [{ type: 'tuple', components: [
        { name: 'invoiceId', type: 'uint256' },
        { name: 'stablecoin', type: 'address' },
        { name: 'initialCollateral', type: 'uint256' },
        { name: 'coinTagContributions', type: 'uint256' },
        { name: 'totalCollateral', type: 'uint256' },
        { name: 'paidOut', type: 'uint256' },
        { name: 'unitsClaimed', type: 'uint256' },
        { name: 'locked', type: 'bool' },
      ]}] },
    { type: 'event', name: 'CollateralDeposited',
      inputs: [{ name: 'invoiceId', type: 'uint256', indexed: true }, { name: 'creator', type: 'address', indexed: true }, { name: 'amount', type: 'uint256' }] },
    { type: 'event', name: 'CollateralIncreased',
      inputs: [{ name: 'invoiceId', type: 'uint256', indexed: true }, { name: 'amount', type: 'uint256' }, { name: 'newTotal', type: 'uint256' }] },
    { type: 'event', name: 'ClaimPaid',
      inputs: [{ name: 'invoiceId', type: 'uint256', indexed: true }, { name: 'unitId', type: 'uint8' }, { name: 'recipient', type: 'address', indexed: true }, { name: 'amount', type: 'uint256' }] },
  ] as const,
}

export const UNIT_CLAIM_CONTRACT = {
  address: CONTRACT_ADDRESSES.unitClaim,
  abi: [
    { type: 'function', name: 'mint', stateMutability: 'nonpayable',
      inputs: [{ name: 'to', type: 'address' }, { name: 'invoiceId', type: 'uint256' }, { name: 'unitId', type: 'uint8' }],
      outputs: [{ name: 'tokenId', type: 'uint256' }] },
    { type: 'function', name: 'claimProofs', stateMutability: 'view',
      inputs: [{ name: 'tokenId', type: 'uint256' }],
      outputs: [{ type: 'tuple', components: [
        { name: 'invoiceId', type: 'uint256' },
        { name: 'unitId', type: 'uint8' },
        { name: 'holder', type: 'address' },
        { name: 'claimedAt', type: 'uint64' },
      ]}] },
    { type: 'function', name: 'tokenOf', stateMutability: 'view',
      inputs: [{ name: 'invoiceId', type: 'uint256' }, { name: 'unitId', type: 'uint8' }], outputs: [{ type: 'uint256' }] },
    { type: 'function', name: 'ownerOf', stateMutability: 'view',
      inputs: [{ name: 'tokenId', type: 'uint256' }], outputs: [{ type: 'address' }] },
    { type: 'event', name: 'UnitClaimMinted',
      inputs: [{ name: 'tokenId', type: 'uint256', indexed: true }, { name: 'invoiceId', type: 'uint256', indexed: true }, { name: 'unitId', type: 'uint8' }, { name: 'holder', type: 'address', indexed: true }] },
  ] as const,
}

export const GRID_MANAGER_CONTRACT = {
  address: CONTRACT_ADDRESSES.gridManager,
  abi: [
    { type: 'function', name: 'createBoard', stateMutability: 'nonpayable',
      inputs: [
        { name: 'invoiceId', type: 'uint256' },
        { name: 'stablecoin', type: 'address' },
        { name: 'winningCoordinates', type: 'uint16[100]' },
        { name: 'unitBindings', type: 'uint8[100]' },
        { name: 'merkleRoot', type: 'bytes32' },
      ], outputs: [] },
    { type: 'function', name: 'grantAccess', stateMutability: 'nonpayable',
      inputs: [{ name: 'invoiceId', type: 'uint256' }, { name: 'user', type: 'address' }], outputs: [] },
    { type: 'function', name: 'submitPair', stateMutability: 'nonpayable',
      inputs: [
        { name: 'invoiceId', type: 'uint256' },
        { name: 'coordinate', type: 'uint16' },
        { name: 'pairA', type: 'uint256' },
        { name: 'pairB', type: 'uint256' },
        { name: 'merkleProof', type: 'bytes32[]' },
      ], outputs: [] },
    { type: 'function', name: 'hasAccess', stateMutability: 'view',
      inputs: [{ name: 'user', type: 'address' }, { name: 'invoiceId', type: 'uint256' }], outputs: [{ type: 'bool' }] },
    { type: 'function', name: 'isCompleted', stateMutability: 'view',
      inputs: [{ name: 'invoiceId', type: 'uint256' }], outputs: [{ type: 'bool' }] },
    { type: 'function', name: 'getBoardUnitsClaimed', stateMutability: 'view',
      inputs: [{ name: 'invoiceId', type: 'uint256' }], outputs: [{ type: 'uint8' }] },
    { type: 'function', name: 'getMerkleRoot', stateMutability: 'view',
      inputs: [{ name: 'invoiceId', type: 'uint256' }], outputs: [{ type: 'bytes32' }] },
    { type: 'event', name: 'BoardCreated',
      inputs: [{ name: 'invoiceId', type: 'uint256', indexed: true }] },
    { type: 'event', name: 'AccessGranted',
      inputs: [{ name: 'invoiceId', type: 'uint256', indexed: true }, { name: 'user', type: 'address', indexed: true }] },
    { type: 'event', name: 'UnitClaimed',
      inputs: [{ name: 'invoiceId', type: 'uint256', indexed: true }, { name: 'unitId', type: 'uint8' }, { name: 'claimer', type: 'address', indexed: true }, { name: 'payout', type: 'uint256' }] },
    { type: 'event', name: 'GameCompleted',
      inputs: [{ name: 'invoiceId', type: 'uint256', indexed: true }] },
  ] as const,
}

export const INVOICE_MANAGER_CONTRACT = {
  address: CONTRACT_ADDRESSES.invoiceManager,
  abi: [
    { type: 'function', name: 'createInvoice', stateMutability: 'nonpayable',
      inputs: [
        { name: 'amount', type: 'uint256' },
        { name: 'stablecoin', type: 'address' },
        { name: 'dueDate', type: 'uint64' },
        { name: 'debtorRef', type: 'bytes32' },
        { name: 'metadataURI', type: 'string' },
      ], outputs: [{ name: 'invoiceId', type: 'uint256' }] },
    { type: 'function', name: 'tokenizeInvoice', stateMutability: 'nonpayable',
      inputs: [
        { name: 'invoiceId', type: 'uint256' },
        { name: 'winningCoordinates', type: 'uint16[100]' },
        { name: 'unitBindings', type: 'uint8[100]' },
        { name: 'merkleRoot', type: 'bytes32' },
      ], outputs: [] },
    { type: 'function', name: 'cancelInvoice', stateMutability: 'nonpayable',
      inputs: [{ name: 'invoiceId', type: 'uint256' }], outputs: [] },
    { type: 'function', name: 'markPaidByPayment', stateMutability: 'nonpayable',
      inputs: [{ name: 'invoiceId', type: 'uint256' }, { name: 'txHash', type: 'bytes32' }], outputs: [] },
    { type: 'function', name: 'getInvoice', stateMutability: 'view',
      inputs: [{ name: 'invoiceId', type: 'uint256' }],
      outputs: [{ type: 'tuple', components: [
        { name: 'id', type: 'uint256' },
        { name: 'creator', type: 'address' },
        { name: 'amount', type: 'uint256' },
        { name: 'stablecoin', type: 'address' },
        { name: 'dueDate', type: 'uint64' },
        { name: 'debtorRef', type: 'bytes32' },
        { name: 'metadataURI', type: 'string' },
        { name: 'status', type: 'uint8' },
      ]}] },
    { type: 'function', name: 'getInvoiceCreator', stateMutability: 'view',
      inputs: [{ name: 'invoiceId', type: 'uint256' }], outputs: [{ type: 'address' }] },
    { type: 'function', name: 'getInvoiceStablecoin', stateMutability: 'view',
      inputs: [{ name: 'invoiceId', type: 'uint256' }], outputs: [{ type: 'address' }] },
    { type: 'event', name: 'InvoiceCreated',
      inputs: [{ name: 'invoiceId', type: 'uint256', indexed: true }, { name: 'creator', type: 'address', indexed: true }, { name: 'amount', type: 'uint256' }, { name: 'stablecoin', type: 'address' }, { name: 'dueDate', type: 'uint64' }] },
    { type: 'event', name: 'InvoiceTokenized',
      inputs: [{ name: 'invoiceId', type: 'uint256', indexed: true }, { name: 'creator', type: 'address', indexed: true }] },
    { type: 'event', name: 'InvoiceStatusChanged',
      inputs: [{ name: 'invoiceId', type: 'uint256', indexed: true }, { name: 'newStatus', type: 'uint8' }] },
    { type: 'event', name: 'InvoiceCancelled',
      inputs: [{ name: 'invoiceId', type: 'uint256', indexed: true }] },
  ] as const,
}

export const COINTAG_MANAGER_CONTRACT = {
  address: CONTRACT_ADDRESSES.coinTagManager,
  abi: [
    { type: 'function', name: 'purchaseCoinTag', stateMutability: 'nonpayable',
      inputs: [{ name: 'invoiceId', type: 'uint256' }, { name: 'stablecoin', type: 'address' }, { name: 'amount', type: 'uint256' }], outputs: [] },
    { type: 'function', name: 'purchaseCoinTag', stateMutability: 'nonpayable',
      inputs: [{ name: 'invoiceId', type: 'uint256' }, { name: 'amount', type: 'uint256' }], outputs: [] },
    { type: 'function', name: 'setAllowlistedStablecoin', stateMutability: 'nonpayable',
      inputs: [{ name: 'token', type: 'address' }, { name: 'allowed', type: 'bool' }], outputs: [] },
    { type: 'function', name: 'setGlobalCoinTagPrice', stateMutability: 'nonpayable',
      inputs: [{ name: 'price', type: 'uint256' }], outputs: [] },
    { type: 'function', name: 'setCustomCoinTagPrice', stateMutability: 'nonpayable',
      inputs: [{ name: 'invoiceId', type: 'uint256' }, { name: 'price', type: 'uint256' }], outputs: [] },
    { type: 'function', name: 'globalCointagPrice', stateMutability: 'view',
      inputs: [], outputs: [{ type: 'uint256' }] },
    { type: 'function', name: 'allowlistedStablecoins', stateMutability: 'view',
      inputs: [{ name: 'token', type: 'address' }], outputs: [{ type: 'bool' }] },
    { type: 'function', name: 'hasAccess', stateMutability: 'view',
      inputs: [{ name: 'user', type: 'address' }, { name: 'invoiceId', type: 'uint256' }], outputs: [{ type: 'bool' }] },
    { type: 'event', name: 'CoinTagPurchased',
      inputs: [{ name: 'invoiceId', type: 'uint256', indexed: true }, { name: 'buyer', type: 'address', indexed: true }, { name: 'amount', type: 'uint256' }, { name: 'creatorAmount', type: 'uint256' }, { name: 'collateralAmount', type: 'uint256' }, { name: 'platformAmount', type: 'uint256' }] },
  ] as const,
}

export const PAYMENT_MANAGER_CONTRACT = {
  address: CONTRACT_ADDRESSES.paymentManager,
  abi: [
    { type: 'function', name: 'payInvoice', stateMutability: 'nonpayable',
      inputs: [{ name: 'invoiceId', type: 'uint256' }, { name: 'amount', type: 'uint256' }], outputs: [] },
    { type: 'function', name: 'isInvoicePaid', stateMutability: 'view',
      inputs: [{ name: 'invoiceId', type: 'uint256' }], outputs: [{ type: 'bool' }] },
    { type: 'event', name: 'InvoicePaid',
      inputs: [{ name: 'invoiceId', type: 'uint256', indexed: true }, { name: 'payer', type: 'address', indexed: true }, { name: 'amount', type: 'uint256' }, { name: 'txHash', type: 'bytes32' }] },
  ] as const,
}
TYPESCRIPT

echo "src/contractConfig.ts written successfully."
echo ""
echo "Addresses:"
echo "  Treasury:          $TREASURY"
echo "  InvoiceNFT:        $INVOICE_NFT"
echo "  CollateralManager: $COLLATERAL_MANAGER"
echo "  UnitClaim:         $UNIT_CLAIM"
echo "  GridManager:       $GRID_MANAGER"
echo "  InvoiceManager:    $INVOICE_MANAGER"
echo "  CoinTagManager:    $COINTAG_MANAGER"
echo "  PaymentManager:    $PAYMENT_MANAGER"
