// AUTO-GENERATED by scripts/write-contract-config.sh - do not edit by hand
// Source: contracts/out/deployed-addresses.json
// Chain: Arc Testnet (5042002)
import { requireChain } from '@/onchain-facts'

export const ARC_TESTNET_ID = 5042002

requireChain(ARC_TESTNET_ID) // validates chain exists

// ── Deployed addresses ────────────────────────────────────────────────────
export const CONTRACT_ADDRESSES = {
  treasury:          '0x0948EE3ce053D3c5d9B0D32F8b349785f6BB1ABD' as `0x${string}`,
  invoiceNFT:        '0xBeff9105ae281aE07943cD263466b34C2737e419' as `0x${string}`,
  collateralManager: '0x7814f445fd67d10B0ab0b6a67141092D4F6C01f1' as `0x${string}`,
  unitClaim:         '0xa4d87D1EFBA64dD07C856eA3989DD8Fa8F267F6E' as `0x${string}`,
  gridManager:       '0x58c702eAa8e273900977230F4c08893d82624D00' as `0x${string}`,
  invoiceManager:    '0x9655A3ca774819B241C4e291ef1cb33759d375A2' as `0x${string}`,
  coinTagManager:    '0x6f9165325973bb47b4FfC1E6bBefD5C74a9cE185' as `0x${string}`,
  paymentManager:    '0x5AbD73D8e5cF84e5D72ecBa67B0AA339076BfE64' as `0x${string}`,
} as const

// ── Per-contract exports (address + minimal ABI) ──────────────────────────

export const TREASURY_CONTRACT = {
  address: CONTRACT_ADDRESSES.treasury,
  abi: [
    { type: 'function', name: 'receiveRevenue', stateMutability: 'nonpayable',
      inputs: [{ name: 'stablecoin', type: 'address' }, { name: 'amount', type: 'uint256' }], outputs: [] },
    { type: 'function', name: 'withdraw', stateMutability: 'nonpayable',
      inputs: [{ name: 'stablecoin', type: 'address' }, { name: 'to', type: 'address' }, { name: 'amount', type: 'uint256' }], outputs: [] },
    { type: 'function', name: 'totalRevenueCollected', stateMutability: 'view',
      inputs: [{ name: 'stablecoin', type: 'address' }], outputs: [{ type: 'uint256' }] },
    { type: 'function', name: 'platformRecipient', stateMutability: 'view',
      inputs: [], outputs: [{ type: 'address' }] },
    { type: 'event', name: 'RevenueReceived',
      inputs: [{ name: 'stablecoin', type: 'address', indexed: true }, { name: 'amount', type: 'uint256' }] },
    { type: 'event', name: 'WithdrawalExecuted',
      inputs: [{ name: 'stablecoin', type: 'address', indexed: true }, { name: 'to', type: 'address', indexed: true }, { name: 'amount', type: 'uint256' }] },
  ] as const,
}

export const INVOICE_NFT_CONTRACT = {
  address: CONTRACT_ADDRESSES.invoiceNFT,
  abi: [
    { type: 'function', name: 'mintInvoiceNFT', stateMutability: 'nonpayable',
      inputs: [{ name: 'invoiceId', type: 'uint256' }, { name: 'creator', type: 'address' }, { name: 'metadataURI', type: 'string' }],
      outputs: [{ name: 'tokenId', type: 'uint256' }] },
    { type: 'function', name: 'getInvoiceNFTData', stateMutability: 'view',
      inputs: [{ name: 'tokenId', type: 'uint256' }],
      outputs: [{ type: 'tuple', components: [
        { name: 'invoiceId', type: 'uint256' },
        { name: 'creator', type: 'address' },
        { name: 'invoiceValue', type: 'uint256' },
        { name: 'stablecoin', type: 'address' },
        { name: 'dueDate', type: 'uint64' },
        { name: 'tokenizedAt', type: 'uint64' },
        { name: 'collateralPool', type: 'address' },
        { name: 'gridBoard', type: 'address' },
        { name: 'totalUnits', type: 'uint16' },
        { name: 'status', type: 'uint8' },
        { name: 'metadataURI', type: 'string' },
        { name: 'debtorRef', type: 'bytes32' },
      ]}] },
    { type: 'function', name: 'ownerOf', stateMutability: 'view',
      inputs: [{ name: 'tokenId', type: 'uint256' }], outputs: [{ type: 'address' }] },
    { type: 'function', name: 'isTransferable', stateMutability: 'view',
      inputs: [{ name: 'tokenId', type: 'uint256' }], outputs: [{ type: 'bool' }] },
    { type: 'event', name: 'InvoiceNFTMinted',
      inputs: [{ name: 'invoiceId', type: 'uint256', indexed: true }, { name: 'to', type: 'address', indexed: true }, { name: 'metadataURI', type: 'string' }] },
    { type: 'event', name: 'InvoiceTokenized',
      inputs: [{ name: 'invoiceId', type: 'uint256', indexed: true }, { name: 'creator', type: 'address', indexed: true }] },
  ] as const,
}

export const COLLATERAL_MANAGER_CONTRACT = {
  address: CONTRACT_ADDRESSES.collateralManager,
  abi: [
    { type: 'function', name: 'depositInitial', stateMutability: 'nonpayable',
      inputs: [{ name: 'invoiceId', type: 'uint256' }, { name: 'stablecoin', type: 'address' }, { name: 'creator', type: 'address' }, { name: 'amount', type: 'uint256' }], outputs: [] },
    { type: 'function', name: 'contribute', stateMutability: 'nonpayable',
      inputs: [{ name: 'invoiceId', type: 'uint256' }, { name: 'amount', type: 'uint256' }], outputs: [] },
    { type: 'function', name: 'payoutClaim', stateMutability: 'nonpayable',
      inputs: [{ name: 'invoiceId', type: 'uint256' }, { name: 'recipient', type: 'address' }], outputs: [{ name: 'payout', type: 'uint256' }] },
    { type: 'function', name: 'totalCollateral', stateMutability: 'view',
      inputs: [{ name: 'invoiceId', type: 'uint256' }], outputs: [{ type: 'uint256' }] },
    { type: 'function', name: 'pools', stateMutability: 'view',
      inputs: [{ name: 'invoiceId', type: 'uint256' }],
      outputs: [{ type: 'tuple', components: [
        { name: 'invoiceId', type: 'uint256' },
        { name: 'stablecoin', type: 'address' },
        { name: 'initialCollateral', type: 'uint256' },
        { name: 'coinTagContributions', type: 'uint256' },
        { name: 'totalCollateral', type: 'uint256' },
        { name: 'paidOut', type: 'uint256' },
        { name: 'unitsClaimed', type: 'uint256' },
        { name: 'locked', type: 'bool' },
      ]}] },
    { type: 'event', name: 'CollateralDeposited',
      inputs: [{ name: 'invoiceId', type: 'uint256', indexed: true }, { name: 'creator', type: 'address', indexed: true }, { name: 'amount', type: 'uint256' }] },
    { type: 'event', name: 'CollateralIncreased',
      inputs: [{ name: 'invoiceId', type: 'uint256', indexed: true }, { name: 'amount', type: 'uint256' }, { name: 'newTotal', type: 'uint256' }] },
    { type: 'event', name: 'ClaimPaid',
      inputs: [{ name: 'invoiceId', type: 'uint256', indexed: true }, { name: 'unitId', type: 'uint8' }, { name: 'recipient', type: 'address', indexed: true }, { name: 'amount', type: 'uint256' }] },
  ] as const,
}

export const UNIT_CLAIM_CONTRACT = {
  address: CONTRACT_ADDRESSES.unitClaim,
  abi: [
    { type: 'function', name: 'mint', stateMutability: 'nonpayable',
      inputs: [{ name: 'to', type: 'address' }, { name: 'invoiceId', type: 'uint256' }, { name: 'unitId', type: 'uint8' }],
      outputs: [{ name: 'tokenId', type: 'uint256' }] },
    { type: 'function', name: 'claimProofs', stateMutability: 'view',
      inputs: [{ name: 'tokenId', type: 'uint256' }],
      outputs: [{ type: 'tuple', components: [
        { name: 'invoiceId', type: 'uint256' },
        { name: 'unitId', type: 'uint8' },
        { name: 'holder', type: 'address' },
        { name: 'claimedAt', type: 'uint64' },
      ]}] },
    { type: 'function', name: 'tokenOf', stateMutability: 'view',
      inputs: [{ name: 'invoiceId', type: 'uint256' }, { name: 'unitId', type: 'uint8' }], outputs: [{ type: 'uint256' }] },
    { type: 'function', name: 'ownerOf', stateMutability: 'view',
      inputs: [{ name: 'tokenId', type: 'uint256' }], outputs: [{ type: 'address' }] },
    { type: 'event', name: 'UnitClaimMinted',
      inputs: [{ name: 'tokenId', type: 'uint256', indexed: true }, { name: 'invoiceId', type: 'uint256', indexed: true }, { name: 'unitId', type: 'uint8' }, { name: 'holder', type: 'address', indexed: true }] },
  ] as const,
}

export const GRID_MANAGER_CONTRACT = {
  address: CONTRACT_ADDRESSES.gridManager,
  abi: [
    { type: 'function', name: 'createBoard', stateMutability: 'nonpayable',
      inputs: [
        { name: 'invoiceId', type: 'uint256' },
        { name: 'stablecoin', type: 'address' },
        { name: 'winningCoordinates', type: 'uint16[100]' },
        { name: 'unitBindings', type: 'uint8[100]' },
        { name: 'merkleRoot', type: 'bytes32' },
      ], outputs: [] },
    { type: 'function', name: 'grantAccess', stateMutability: 'nonpayable',
      inputs: [{ name: 'invoiceId', type: 'uint256' }, { name: 'user', type: 'address' }], outputs: [] },
    { type: 'function', name: 'submitPair', stateMutability: 'nonpayable',
      inputs: [
        { name: 'invoiceId', type: 'uint256' },
        { name: 'coordinate', type: 'uint16' },
        { name: 'pairA', type: 'uint256' },
        { name: 'pairB', type: 'uint256' },
        { name: 'merkleProof', type: 'bytes32[]' },
      ], outputs: [] },
    { type: 'function', name: 'hasAccess', stateMutability: 'view',
      inputs: [{ name: 'user', type: 'address' }, { name: 'invoiceId', type: 'uint256' }], outputs: [{ type: 'bool' }] },
    { type: 'function', name: 'isCompleted', stateMutability: 'view',
      inputs: [{ name: 'invoiceId', type: 'uint256' }], outputs: [{ type: 'bool' }] },
    { type: 'function', name: 'getBoardUnitsClaimed', stateMutability: 'view',
      inputs: [{ name: 'invoiceId', type: 'uint256' }], outputs: [{ type: 'uint8' }] },
    { type: 'function', name: 'getMerkleRoot', stateMutability: 'view',
      inputs: [{ name: 'invoiceId', type: 'uint256' }], outputs: [{ type: 'bytes32' }] },
    { type: 'event', name: 'BoardCreated',
      inputs: [{ name: 'invoiceId', type: 'uint256', indexed: true }] },
    { type: 'event', name: 'AccessGranted',
      inputs: [{ name: 'invoiceId', type: 'uint256', indexed: true }, { name: 'user', type: 'address', indexed: true }] },
    { type: 'event', name: 'UnitClaimed',
      inputs: [{ name: 'invoiceId', type: 'uint256', indexed: true }, { name: 'unitId', type: 'uint8' }, { name: 'claimer', type: 'address', indexed: true }, { name: 'payout', type: 'uint256' }] },
    { type: 'event', name: 'GameCompleted',
      inputs: [{ name: 'invoiceId', type: 'uint256', indexed: true }] },
  ] as const,
}

export const INVOICE_MANAGER_CONTRACT = {
  address: CONTRACT_ADDRESSES.invoiceManager,
  abi: [
    {
      type: 'function',
      name: 'tokenizeInvoice',
      stateMutability: 'nonpayable',
      inputs: [
        { name: 'amount', type: 'uint256' },
        { name: 'stablecoin', type: 'address' },
        { name: 'dueDate', type: 'uint64' },
        { name: 'debtorRef', type: 'bytes32' },
        { name: 'metadataURI', type: 'string' },
        { name: 'winningCoordinates', type: 'uint16[100]' },
        { name: 'unitBindings', type: 'uint8[100]' },
        { name: 'merkleRoot', type: 'bytes32' },
      ],
      outputs: [{ name: 'invoiceId', type: 'uint256' }],
    },
    {
      type: 'function',
      name: 'getInvoice',
      stateMutability: 'view',
      inputs: [{ name: 'invoiceId', type: 'uint256' }],
      outputs: [
        {
          type: 'tuple',
          components: [
            { name: 'id', type: 'uint256' },
            { name: 'creator', type: 'address' },
            { name: 'amount', type: 'uint256' },
            { name: 'stablecoin', type: 'address' },
            { name: 'dueDate', type: 'uint64' },
            { name: 'debtorRef', type: 'bytes32' },
            { name: 'metadataURI', type: 'string' },
            { name: 'status', type: 'uint8' },
          ],
        },
      ],
    },
    {
      type: 'function',
      name: 'getInvoiceCreator',
      stateMutability: 'view',
      inputs: [{ name: 'invoiceId', type: 'uint256' }],
      outputs: [{ type: 'address' }],
    },
    {
      type: 'function',
      name: 'getInvoiceStablecoin',
      stateMutability: 'view',
      inputs: [{ name: 'invoiceId', type: 'uint256' }],
      outputs: [{ type: 'address' }],
    },
    {
      type: 'event',
      name: 'InvoiceTokenized',
      inputs: [
        { name: 'invoiceId', type: 'uint256', indexed: true },
        { name: 'creator', type: 'address', indexed: true },
      ],
    },
    {
      type: 'event',
      name: 'InvoiceStatusChanged',
      inputs: [
        { name: 'invoiceId', type: 'uint256', indexed: true },
        { name: 'newStatus', type: 'uint8' },
      ],
    },
  ] as const,
}

export const COINTAG_MANAGER_CONTRACT = {
  address: CONTRACT_ADDRESSES.coinTagManager,
  abi: [
    { type: 'function', name: 'purchaseCoinTag', stateMutability: 'nonpayable',
      inputs: [{ name: 'invoiceId', type: 'uint256' }, { name: 'stablecoin', type: 'address' }, { name: 'amount', type: 'uint256' }], outputs: [] },
    { type: 'function', name: 'purchaseCoinTag', stateMutability: 'nonpayable',
      inputs: [{ name: 'invoiceId', type: 'uint256' }, { name: 'amount', type: 'uint256' }], outputs: [] },
    { type: 'function', name: 'setAllowlistedStablecoin', stateMutability: 'nonpayable',
      inputs: [{ name: 'token', type: 'address' }, { name: 'allowed', type: 'bool' }], outputs: [] },
    { type: 'function', name: 'setGlobalCoinTagPrice', stateMutability: 'nonpayable',
      inputs: [{ name: 'price', type: 'uint256' }], outputs: [] },
    { type: 'function', name: 'setCustomCoinTagPrice', stateMutability: 'nonpayable',
      inputs: [{ name: 'invoiceId', type: 'uint256' }, { name: 'price', type: 'uint256' }], outputs: [] },
    { type: 'function', name: 'globalCointagPrice', stateMutability: 'view',
      inputs: [], outputs: [{ type: 'uint256' }] },
    { type: 'function', name: 'allowlistedStablecoins', stateMutability: 'view',
      inputs: [{ name: 'token', type: 'address' }], outputs: [{ type: 'bool' }] },
    { type: 'function', name: 'hasAccess', stateMutability: 'view',
      inputs: [{ name: 'user', type: 'address' }, { name: 'invoiceId', type: 'uint256' }], outputs: [{ type: 'bool' }] },
    { type: 'event', name: 'CoinTagPurchased',
      inputs: [{ name: 'invoiceId', type: 'uint256', indexed: true }, { name: 'buyer', type: 'address', indexed: true }, { name: 'amount', type: 'uint256' }, { name: 'creatorAmount', type: 'uint256' }, { name: 'collateralAmount', type: 'uint256' }, { name: 'platformAmount', type: 'uint256' }] },
  ] as const,
}

/** @deprecated Retired - direct ERC-20 transfer used instead */
export const PAYMENT_MANAGER_CONTRACT = {
  address: CONTRACT_ADDRESSES.paymentManager,
  abi: [
    { type: 'function', name: 'payInvoice', stateMutability: 'nonpayable',
      inputs: [{ name: 'invoiceId', type: 'uint256' }, { name: 'amount', type: 'uint256' }], outputs: [] },
    { type: 'function', name: 'isInvoicePaid', stateMutability: 'view',
      inputs: [{ name: 'invoiceId', type: 'uint256' }], outputs: [{ type: 'bool' }] },
    { type: 'event', name: 'InvoicePaid',
      inputs: [{ name: 'invoiceId', type: 'uint256', indexed: true }, { name: 'payer', type: 'address', indexed: true }, { name: 'amount', type: 'uint256' }, { name: 'txHash', type: 'bytes32' }] },
  ] as const,
}

// TEMPORARY COMPATIBILITY ALIASES
// These exist so out-of-scope legacy components compile.
// They will be removed when Dashboard.tsx and
// TokenizeExternal.tsx are individually rewired.

/** @deprecated Use INVOICE_MANAGER_CONTRACT */
export const INVOICE_CONTRACT = INVOICE_MANAGER_CONTRACT

/** @deprecated Use INVOICE_NFT_CONTRACT */
export const STRYK_NFT_CONTRACT = INVOICE_NFT_CONTRACT

/** @deprecated Use GRID_MANAGER_CONTRACT */
export const STRYK_GRID_CONTRACT = GRID_MANAGER_CONTRACT

